on:
  push:
    tags:
      - '*'

name: Publish

jobs:
  publish:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: mkdir -p dist && tar --exclude dist --exclude .git -czvf dist/artifact-test.tar.gz .

    - id: version
      name: version
      run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/artifact-test.tar.gz
        asset_name: artifact-test.tar.gz
        asset_content_type: application/gzip